INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, GENDER, DATE_OF_BIRTH, DEPARTMENT)
VALUES ('John', 'One', 'Male', CAST('1993-04-06' AS DATE), 'IT');

INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, GENDER, DATE_OF_BIRTH, DEPARTMENT)
VALUES ('John', 'Two', 'Male', CAST('1995-07-20' AS DATE), 'Sales');

INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, GENDER, DATE_OF_BIRTH, DEPARTMENT)
VALUES ('John', 'Three', 'Male', CAST('2000-05-06' AS DATE), 'IT');

INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, GENDER, DATE_OF_BIRTH, DEPARTMENT)
VALUES ('John', 'Four', 'Female', CAST('1990-08-06' AS DATE), 'Accounts');

INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, GENDER, DATE_OF_BIRTH, DEPARTMENT)
VALUES ('John', 'Five', 'Male', CAST('1994-01-06' AS DATE), 'Accounts');

INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, GENDER, DATE_OF_BIRTH, DEPARTMENT)
VALUES ('John', 'Six', 'Male', CAST('2000-02-06' AS DATE), 'IT');

INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, GENDER, DATE_OF_BIRTH, DEPARTMENT)
VALUES ('Jane', 'Seven', 'Female', CAST('2001-09-06' AS DATE), 'IT');

INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, GENDER, DATE_OF_BIRTH, DEPARTMENT)
VALUES ('John', 'Eight', 'Male', CAST('1994-07-26' AS DATE), 'Sales');

INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, GENDER, DATE_OF_BIRTH, DEPARTMENT)
VALUES ('Jane', 'Nine', 'Female', CAST('2012-06-11' AS DATE), 'Sales');

INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, GENDER, DATE_OF_BIRTH, DEPARTMENT)
VALUES ('Jane', 'Ten', 'Female', CAST('1994-05-09' AS DATE), 'IT');